language: go
go:
- 1.x
cache:
  pip: true
  directories:
  - "$HOME/.nvm"
  - "$HOME/.local"
before_cache:
- rm -f $HOME/.npm/anonymous-cli-metrics.json
matrix:
  include:
  - name: "python2"
    sudo: false
    before_install:
    - pyenv global 2.7
  - name: "python3"
    before_install:
    - pyenv global 3.6
  - name: "bazel"
    sudo: true
    dist: xenial
    before_install:
    - pyenv global 3.7
    - |
      BAZEL_VERSION=0.27.0
      OS="${TRAVIS_OS_NAME}"
      if [[ "${OS}" == "osx" ]]; then
        OS=darwin
      else
        sysctl kernel.unprivileged_userns_clone=1
      fi
      URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${OS}-x86_64.sh"
      wget -O install.sh "${URL}"
      chmod +x install.sh
      ./install.sh --user
      rm -f install.sh
    script:
    - |
      bazel \
        --output_base=$HOME/.cache/bazel \
        --host_jvm_args=-Xmx500m \
        --host_jvm_args=-Xms500m \
        test \
        --local_resources=400,1,1.0 \
        //...
    - |
      bazel \
        --output_base=$HOME/.cache/bazel \
        --host_jvm_args=-Xmx500m \
        --host_jvm_args=-Xms500m \
        build \
        --local_resources=400,1,1.0 \
        -c opt \
        //:martian
before_install:
- python --version
- pip --version
before_script:
- nvm install --lts node
- npm install -g npm@^6.9
- pip install --user pylint
script:
- "./.travis.gofmt.sh"
- make test
- make longtests
- pylint adapters/python/martian_shell.py
- pylint adapters/python/martian.py
- pylint test/martian_test.py
- make all tarball
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dBZPhakddKqoQhvJseeIHpbWyyrmZjdZ1oOsa+dR8v+yyIw1Lf9tVk4+3cearrbelxYf65ZqkQXQPWw2uZYvCQbNzMtU9hhzOwBi8/Wb8gWXlcNDjQso8iLP3Z77DeuyYg4CA7EiSbvIIFaFcUtucTAu5b0Wa0uPj7/PX37CT/6oGM9h4jdocSeI65XmB0YuraSNDAHaurWcwLZZG9PNeENTgbjvS218SUkg2HFFTeApLZCaNyxWYxEfsUcu5VXKCpSpsLm82u7XGuNVDhavMjxvH6SG1PgIdPf31N0ok5UocUVl0z4lrlT2/YEwLbI5XyLxFvqcdDN1MKvQREirPCOMMSdJivDTv87gLZGHev/C6+rEJaSXhqF158KN7VWSf9YCjNCiWgi5/E5RDdVDzmlGsLCWn+M1owWFbKAkdM0xCntcfN8Yx3jFCd2NxhKFsQOlpYZMCKmD0PWDqCUFIizkpli2jXeRJvm5NNu5iyjIJ5xJCfH56vBJMksQK9cdE4jqjz1ZuXo7AQrM8NHPOeAlp+GkfHkBdfja5kFvoP9mYANzViXinvYqxK/qnoo+Jd8XzVE+R/D0t6V9bHuoRDDc/nbvXJPxqSxhnPNUvzJpTkT5UYE3XC3Y5HicHBq09ulbMItKHWAu6J0nyefLNvnLmptTa0WqjSefPJv9kIo=
  file_glob: true
  file: martian-$TRAVIS_TAG-*.tar.*z
  on:
    repo: martian-lang/martian
    tags: true
